language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t rohitwagh15/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rohitwagh15/react-test npm test

after_success:
  - docker build -t rohitwagh15/multi-client ./client
  - docker build -t rohitwagh15/multi-nginx ./nginx
  - docker build -t rohitwagh15/multi-server ./server
  - docker build -t rohitwagh15/multi-worker ./worker

  #pusing image to push docker hub using CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rohitwagh15/multi-clint
  - docker push rohitwagh15/multi-nginx
  - docker push rohitwagh15/multi-server
  - docker push rohitwagh15/multi-worker

